# Generated by Django 5.2.1 on 2025-06-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='Image'),
        ),
    ]
