# Generated by Django 5.2.1 on 2025-06-04 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_offer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-created_at'], 'verbose_name': 'تشكيلة', 'verbose_name_plural': 'التشكيلات'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'اللون', 'verbose_name_plural': 'الألوان'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at'], 'verbose_name': 'عرض', 'verbose_name_plural': 'العروض'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', 'created_at'], 'verbose_name': 'صورة المنتج', 'verbose_name_plural': 'صور المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'نسخة المنتج', 'verbose_name_plural': 'نسخ المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقييم', 'verbose_name_plural': 'التقييمات'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name'], 'verbose_name': 'المقاس', 'verbose_name_plural': 'المقاسات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='product.category', verbose_name='القسم الرئيسي'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='الوصف بالعربية'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='الوصف بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(upload_to='collections/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(related_name='collections', to='product.product', verbose_name='المنتجات'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(help_text='كود اللون بصيغة hex مثل #FF0000', max_length=10, verbose_name='كود اللون'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name_ar',
            field=models.CharField(max_length=50, verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='الوصف بالعربية'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='الوصف بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='صورة العرض'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(related_name='offers', to='product.product', verbose_name='المنتجات'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title_ar',
            field=models.CharField(max_length=200, verbose_name='العنوان بالعربية'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='العنوان بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('new', 'جديد'), ('sale', 'تخفيض'), ('hot', 'رائج'), ('exclusive', 'حصري')], max_length=20, null=True, verbose_name='الشارة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='الوصف بالعربية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='الوصف بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='جديد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='عرض خاص'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=200, verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر القديم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الحالي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='صورة رئيسية'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الخاص'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='المقاس'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='رمز المنتج'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية المتوفرة'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='التعليق'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='معتمد'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=20, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name_ar',
            field=models.CharField(max_length=20, verbose_name='الاسم بالعربية'),
        ),
    ]
