# Generated by Django 5.2.1 on 2025-06-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='العنوان بالإنجليزية')),
                ('title_ar', models.CharField(max_length=100, verbose_name='العنوان بالعربية')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان الفرعي')),
                ('subtitle_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان الفرعي بالإنجليزية')),
                ('subtitle_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان الفرعي بالعربية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='الوصف بالإنجليزية')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='الوصف بالعربية')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='الصورة')),
                ('link', models.URLField(blank=True, null=True, verbose_name='الرابط')),
                ('link_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='نص الرابط')),
                ('link_text_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='نص الرابط بالعربية')),
                ('page', models.CharField(choices=[('home', 'الصفحة الرئيسية'), ('men', 'صفحة الرجال'), ('women', 'صفحة النساء'), ('kids', 'صفحة الأطفال'), ('collection', 'صفحة التشكيلات'), ('offers', 'صفحة العروض')], default='home', max_length=20, verbose_name='الصفحة')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'سلايدر',
                'verbose_name_plural': 'السلايدرز',
                'ordering': ['page', 'order'],
            },
        ),
    ]
